### YamlMime:YamlDocument
documentType: LandingData
title: "PlayFab Config Features"
metadata:
  title: "PlayFab Config Features"
  author: v-thopra  
  description: Landing page for PlayFab Config features.
  ms.author: v-thopra
  ms.date: 11/13/2018
  ms.topic: landing-page
  ms.prod: playfab  
  keywords: playfab, config
  ms.localizationpriority: medium
sections:
- items:
  - type: list
    style: cards
    className: cardsF
    columns: 3
    items:
    - image:
        src: "/gaming/playfab/features/media/feature-game-manager.svg"
        text: "PlayFab Config Features - Game Manager card image"        
      title: "Game Manager"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/config/gamemanager/'>Overview</a></p><p><a href='/gaming/playfab/features/config/gamemanager/quickstart'>Quickstart</a></p><p><a href='/gaming/playfab/features/config/gamemanager/tutorials'>Tutorials</a></p>"
    - image:
        src: "/gaming/playfab/features/media/feature-titledata.svg"
        text: "PlayFab Config Features - Title Data card image"        
      title: "Title Data"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/config/titledata/'>Overview</a></p><p><a href='/gaming/playfab/features/config/titledata/quickstart'>Quickstart</a></p><p><a href='/gaming/playfab/features/config/titledata/tutorials'>Tutorials</a></p>"
    - image:
        src: "/gaming/playfab/features/media/feature-dev-test-live.svg"
        text: "PlayFab Config Features - Dev-Test-Live card image"        
      title: "Dev-Test-Live"
      html: "<p style='color: #7f7f7f'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p><p><a href='/gaming/playfab/features/config/dev-test-live/'>Overview</a></p><p><a href='/gaming/playfab/features/config/dev-test-live/quickstart'>Quickstart</a></p><p><a href='/gaming/playfab/features/config/dev-test-live/tutorials'>Tutorials</a></p>"
